spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sionicdb}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:sionic}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
